language: java
jdk:
  -openjdk8

branches:
  only:
    master

# Travis CI server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r samlasoft-springboot-webservice *
  - mkdir -p deploy
  - mv samlasoft-springboot-webservice.zip deploy/samlasoft-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: samlasoft-webservice-build
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deploy: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: samlasoft-webservice-build
    key: samlasoft-springboot-webservice.zip
    bundle_type: zip
    application: springboot-webservice # AWS CodeDeploy에 등록한 application 이름
    deployment_group: springboot-webservice-group # AWS CodeDeploy에 등록한 group 이름
    region: ap-northeast-2
    wait-until-deployed: true

# notice CI execute complet send mail.
notifications:
  email:
    recipients:
      - samlak72@gmail.com
