version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh # stop not connected nginx springboot
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # start new springboot not connected port
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # new stpringboot status check
      timeout: 60
      runas: ec2-user

